version: 2
updates:
  - directory: /
    labels:
      - dependencies
    package-ecosystem: yarn
    reviewers:
      - kurone-kito
    assignees:
      - kurone-kito
    schedule:
      interval: weekly
